name: "Output workflow"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  output:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["develop"]
    steps:
#      - name: "Output github"
#        run: echo "${{ toJSON(github) }}"

      - name: "Checkout code from develop"
        uses: actions/checkout@v4 # v4.1.0
        with:
          ref: develop
#          token: ${{ secrets.CI_KEY }}
          fetch-depth: 0

      - name: "Merge master into develop"
        run: |
          git config --global user.name 'allotomation' && \
          git config --global user.email 'serviceaccount.allotomation@allopneus.com' && \
          git merge origin/main --no-ff && \
          gti push origin develop

#      - name: "Notify failure on Teams channel"
#        if: failure()
#        # JSON format: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using
#        run: |
#          echo "Notify failure on Teams channel"
#          cat << EOF > message.json
#          {
#            "@type":"MessageCard",
#            "@context":"https://schema.org/extensions",
#            "summary":"Fail to merge master into ${{ matrix.branch }} for hevea-stations-api",
#            "title": "[hevea-stations-api] Fail to merge branches : master → ${{ matrix.branch }}",
#            "themeColor":"ff6600",
#            "potentialAction":[
#              {
#                "@type":"OpenUri",
#                "name":"Voir le lien",
#                "targets":[
#                  {
#                    "os":"default",
#                    "uri":"https://rick.roll"
#                  }
#                ]
#              }
#             ]
#          }
#          EOF
#          curl -X POST https://allopneus.webhook.office.com/webhookb2/e4228484-8970-4176-95a0-719bc0f259d8@ac205d14-f9ff-4d7a-8129-aa50d3988c68/IncomingWebhook/b100761b92c841caafaec419b2d9b52a/0f9dd978-347f-4955-8e79-48bd2ae1c980 --header 'Content-Type: application/json' -d @message.json

      - name: "Notify failure on Teams channel"
        if: failure()
        run: |
          echo "Notify failure on Teams channel"
          cat << EOF > message.json
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "Test Message:  in progress...",
            "sections": [{
              "activityTitle": "Larry Bryant created a new task",
              "activitySubtitle": "On Project Tango",
              "activityImage": "https://adaptivecards.io/content/cats/3.png",
              "facts": [{
                "name": "Assigned to",
                "value": "Unassigned"
              }, {
                "name": "Due date",
                "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
              }, {
                "name": "Status",
                "value": "Not started"
              }],
              "markdown": true
            }],
            "potentialAction": [{
              "@type": "ActionCard",
              "name": "Add a comment",
              "inputs": [{
                "@type": "TextInput",
                "id": "comment",
                "isMultiline": false,
                "title": "Add a comment here for this task"
              }],
              "actions": [{
                "@type": "HttpPOST",
                "name": "Add comment",
                "target": "https://learn.microsoft.com/outlook/actionable-messages"
              }]
            }, {
              "@type": "ActionCard",
              "name": "Set due date",
              "inputs": [{
                "@type": "DateInput",
                "id": "dueDate",
                "title": "Enter a due date for this task"
              }],
              "actions": [{
                "@type": "HttpPOST",
                "name": "Save",
                "target": "https://learn.microsoft.com/outlook/actionable-messages"
              }]
            }, {
              "@type": "OpenUri",
              "name": "Learn More",
              "targets": [{
                "os": "default",
                "uri": "https://learn.microsoft.com/outlook/actionable-messages"
              }]
            }, {
              "@type": "ActionCard",
              "name": "Change status",
              "inputs": [{
                "@type": "MultichoiceInput",
                "id": "list",
                "title": "Select a status",
                "isMultiSelect": "false",
                "choices": [{
                  "display": "In Progress",
                  "value": "1"
                }, {
                  "display": "Active",
                  "value": "2"
                }, {
                  "display": "Closed",
                  "value": "3"
                }]
              }],
              "actions": [{
                "@type": "HttpPOST",
                "name": "Save",
                "target": "https://learn.microsoft.com/outlook/actionable-messages"
              }]
            }]
          }
          EOF
          curl -X POST https://allopneus.webhook.office.com/webhookb2/e4228484-8970-4176-95a0-719bc0f259d8@ac205d14-f9ff-4d7a-8129-aa50d3988c68/IncomingWebhook/b100761b92c841caafaec419b2d9b52a/0f9dd978-347f-4955-8e79-48bd2ae1c980 --header 'Content-Type: application/json' -d @message.json
