name: "Output workflow"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
#            - name: "Output github"
#              run: echo "${{ toJSON(github) }}"

            - name: "Checkout code from develop"
              uses: actions/checkout@v4 # v4.1.0
              with:
                ref: develop
#                token: ${{ secrets.CI_KEY }}
                fetch-depth: 0

            - name: "Merge master into develop"
              run: |
                git config --global user.name 'allotomation' && \
                git config --global user.email 'serviceaccount.allotomation@allopneus.com' && \
                git merge origin/main --no-ff && \
                git push origin develop
                echo "MERGE DONE !"
#            - name: "Notify Teams"
#              if: steps.changed-files-specific.outputs.added_files != ''
#              # JSON format: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using
#              run: |
#                echo "Detect new article: ${{ steps.changed-files-specific.outputs.added_files }}"
#                echo "Notify Teams"
#                cat << EOF > message.json
#                {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Nouvel article", "title": "Nouvel article : ${{ env.article_title }}", "themeColor":"00ff00","potentialAction":[{"@type":"OpenUri","name":"Voir le nouvel article","targets":[{"os":"default","uri":"https://blog-tech.allopneus.com/posts/${{ env.article_basename }}/"}]}]}
#                EOF
#                curl -X POST https://allopneus.webhook.office.com/webhookb2/275890a4-0e3f-4010-80ae-ade67f9c71f6@ac205d14-f9ff-4d7a-8129-aa50d3988c68/IncomingWebhook/a07bf551be2648c0ac520524ec536c4b/dfed3653-db39-4796-ba50-2af3d4254b4d --header 'Content-Type: application/json' -d @message.json

